name: Frontend CI - Build & Push

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_frontend:
    uses: ./.github/workflows/reusable-acr-build.yml
    with:
      context: frontend
      dockerfile: frontend/Dockerfile
      image_name: frontend
      tags: latest
    secrets: inherit
